# Generated by Django 5.2.11 on 2026-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Music', 'Music'), ('Sports', 'Sports'), ('Business', 'Business')], default='Tech', max_length=50),
        ),
    ]
