# Generated by Django 5.2.11 on 2026-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], default='Regular', max_length=20),
        ),
    ]
