# Generated by Django 5.2.11 on 2026-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
