# Generated by Django 5.2.11 on 2026-05-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_userprofile_is_email_verified_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], max_length=20),
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickettier'),
        ),
    ]
