# Generated by Django 5.2.11 on 2026-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
